FROM python:3.11-bookworm

WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

# COPY . /app
COPY deai /app/deai
COPY pyproject.toml /app
COPY configs /app/configs
COPY tests /app/tests

RUN pip install -e .

RUN mkdir -p /app/logs

# todo. run the tests

SHELL ["/bin/bash", "-c"]